app:
  name: cartservice
  version: v0.4.1
  replicaCount: 2

image:
  repository: gcr.io/google-samples/microservices-demo/cartservice

container:
  port: 7070
  env:
  - name: PORT
    value: "7070"
  - name: REDIS_ADDR
    value: "redis-cart:6379"

service:
  type: ClusterIP
  port: 7070