app:
  name: productcatalogservice
  version: v0.4.1
  replicaCount: 2

image:
  repository: gcr.io/google-samples/microservices-demo/productcatalogservice

container:
  port: 3550
  env:
  - name: PORT
    value: "3550"
  - name: DISABLE_STATS
    value: "1"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"

service:
  type: ClusterIP
  port: 3550